---
- name: Install apache webserver
  hosts: webservers
  tasks:

  - name: Install the package
    yum:
      name: "{{ item }}"
      state: present
    loop: 
    - httpd
    - php

  - name: Start the service httpd
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop: 
    - httpd
    - firewalld

  - name: create new file index.html
    file:
      path: /var/www/html/index.html
      state: touch

  - name: create directory for html file
    copy:
      content: 'Ini adalah websever dengan {{ ansible_fqdn }}'
      dest: /var/www/html/index.html


  - name: open firewall for port 80
    firewalld:
      service: http
      state: enabled
      permanent: yes
      immediate: yes

  - name: restart httpd
    service:
      name: httpd
      state: restarted
